import type { HaircutItem, BeardStyleItem, ColorOptionItem, FaceShape } from './types.ts';

export const FACE_SHAPES_GUIDE: Record<FaceShape, { title: string; description: string; characteristics: string; icon: string }> = {
  Oval: {
    title: 'Rosto Oval',
    description: 'Proporções equilibradas, queixo ligeiramente arredondado e testa ligeiramente mais larga que a mandíbula.',
    characteristics: 'Versátil, combina com quase todos os estilos de corte e barba.',
    icon: '🥚',
  },
  Redondo: {
    title: 'Rosto Redondo',
    description: 'Comprimento e largura similares, com ângulos suaves e maçãs do rosto proeminentes.',
    characteristics: 'Beneficia-se de cortes com volume no topo e laterais baixas para alongar.',
    icon: '⭕',
  },
  Quadrado: {
    title: 'Rosto Quadrado',
    description: 'Mandíbula bem marcada e angular, com testa e maxilar na mesma proporção de largura.',
    characteristics: 'Transmite força e masculinidade; combina com fades limpos e topetes.',
    icon: '🔲',
  },
  Retangular: {
    title: 'Rosto Retangular / Oblongo',
    description: 'Rosto mais comprido que largo, com queixo e mandíbula retos.',
    characteristics: 'Harmoniza com cortes com franja lateral e barbas curtas ou médias que preenchem as laterais.',
    icon: '📱',
  },
  Triangular: {
    title: 'Rosto Triangular',
    description: 'Mandíbula mais larga e proeminente afinando em direção à testa.',
    characteristics: 'Funciona muito bem com volume no topo e texturização para balancear a mandíbula.',
    icon: '🔺',
  },
  Coracao: {
    title: 'Rosto Coração / Triangular Invertido',
    description: 'Testa mais larga com queixo afinado ou pontudo.',
    characteristics: 'Barba cheia ou média equilibra o queixo estreito, combinando com cortes médios.',
    icon: '🤍',
  },
  'Nao sei': {
    title: 'Identificação Rápida',
    description: 'Observe a linha do seu maxilar e da testa no espelho.',
    characteristics: 'Nossas recomendações aplicarão princípios universais de harmonia facial.',
    icon: '❓',
  },
};

const BASE_NEGATIVE_PROMPT =
  'new person, different person, different identity, new face, face replacement, face swap, altered identity, changed facial structure, different eyes, different eyebrows, different nose, different mouth, different lips, different jaw, different skin, different skin tone, beautified face, younger face, older face, different expression, portrait of another person, new human, full body, new background, different clothing, text to image, synthetic portrait, AI generated person, celebrity, model, generic male, generic face, deformed face, unrealistic facial features, cartoon, illustration, 3d render, blurry, distorted, low quality, deformed ears';

export const HAIRCUTS_CATALOG: HaircutItem[] = [
  {
    id: 'low-fade',
    name: 'Low Fade',
    category: 'Degrade',
    description: 'Degradê sutil que começa logo acima da orelha e nuca, preservando densidade.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Medio',
    styleCompatibility: ['Classico', 'Moderno', 'Executivo', 'Degrade', 'Natural'],
    idealLength: 'Curto',
    changeImpact: 'Pouco',
    suggestedServiceKeywords: ['corte', 'degrade', 'fade', 'social'],
    stylingTips: 'Manutenção a cada 15 a 20 dias para manter a transição limpa.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's low fade haircut, smooth temple taper fade, natural textured top volume, crisp razor hairline, ultra-detailed human hair strands, authentic barber styling, 8k uhd, soft studio lighting.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'mid-fade',
    name: 'Mid Fade',
    category: 'Degrade',
    description: 'Degradê na altura média da cabeça, equilibrando contraste e versatilidade.',
    compatibleFaceShapes: ['Oval', 'Redondo', 'Quadrado', 'Triangular', 'Nao sei'],
    maintenanceLevel: 'Medio',
    styleCompatibility: ['Moderno', 'Casual', 'Degrade', 'Marcante'],
    idealLength: 'Curto',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'degrade', 'fade', 'moderno'],
    stylingTips: 'Excelente para quem quer presença marcante sem perder elegância.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's mid fade haircut, clean smooth gradient transition on sides, styled textured top, sharp natural hairline, realistic hair follicles, professional barber finish, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'high-fade',
    name: 'High Fade',
    category: 'Degrade',
    description: 'Degradê alto e contrastante, com laterais bem curtas iniciando perto do topo.',
    compatibleFaceShapes: ['Redondo', 'Oval', 'Quadrado'],
    maintenanceLevel: 'Bastante',
    styleCompatibility: ['Moderno', 'Despojado', 'Degrade', 'Marcante'],
    idealLength: 'Curto',
    changeImpact: 'Radical',
    suggestedServiceKeywords: ['corte', 'high fade', 'degrade'],
    stylingTips: 'Exige manutenção frequente (10 a 15 dias) para preservar o contraste nítido.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's high fade haircut, high-contrast close-trimmed sides, sharp blended gradient, textured cropped top, crisp hairline contour, authentic human hair texture, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'skin-fade',
    name: 'Skin Fade (Navalhado)',
    category: 'Degrade',
    description: 'Degradê raspado na navalha desde a pele, proporcionando máxima nitidez.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Redondo', 'Triangular'],
    maintenanceLevel: 'Bastante',
    styleCompatibility: ['Moderno', 'Degrade', 'Marcante'],
    idealLength: 'Curto',
    changeImpact: 'Radical',
    suggestedServiceKeywords: ['navalhado', 'corte', 'fade'],
    stylingTips: 'Finalize com loção pós-barba nas laterais e pomada matte no topo.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's skin fade razor haircut, seamless bald skin taper on lower sides, smooth gradient blend to textured top, razor-sharp edge lineup, hyperrealistic hair strands.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'taper-fade',
    name: 'Taper Fade',
    category: 'Classico Moderno',
    description: 'Degradê suave restrito apenas às costeletas e à nuca, mantendo as laterais naturais.',
    compatibleFaceShapes: ['Oval', 'Retangular', 'Quadrado', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Pouco',
    styleCompatibility: ['Classico', 'Executivo', 'Casual', 'Natural'],
    idealLength: 'Medio',
    changeImpact: 'Pouco',
    suggestedServiceKeywords: ['corte', 'social', 'classico', 'taper'],
    stylingTips: 'Perfeito para ambientes formais e quem prefere maior intervalo entre cortes.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's classic taper fade haircut, dense natural sides, clean subtle taper at temples and neckline, neat scissor-shaped top, natural hair flow, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'buzz-cut',
    name: 'Buzz Cut',
    category: 'Minimalista',
    description: 'Corte militar uniforme raspado por completo, destacando traços faciais.',
    compatibleFaceShapes: ['Oval', 'Quadrado'],
    maintenanceLevel: 'Pouco',
    styleCompatibility: ['Casual', 'Curto', 'Marcante'],
    idealLength: 'Curto',
    changeImpact: 'Radical',
    suggestedServiceKeywords: ['maquina', 'corte militar', 'corte'],
    stylingTips: 'Zero trabalho diário para pentear; ideal para rotinas aceleradas.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's military buzz cut, even short clipper buzz, clean razor lineup at forehead and temples, hyper-detailed stubble hair follicles, authentic scalp texture.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'crew-cut',
    name: 'Crew Cut',
    category: 'Classico',
    description: 'Corte clássico curto com topo ligeiramente mais alto na frente e laterais limpas.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular', 'Nao sei'],
    maintenanceLevel: 'Pouco',
    styleCompatibility: ['Classico', 'Executivo', 'Casual', 'Curto'],
    idealLength: 'Curto',
    changeImpact: 'Pouco',
    suggestedServiceKeywords: ['social', 'corte', 'executivo'],
    stylingTips: 'Finalização rápida com pouco creme ou pasta modeladora.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's classic crew cut, short tapered sides, slight upward lift in front hairline, neat scissor-crafted proportions, natural matte hair texture, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'french-crop',
    name: 'French Crop',
    category: 'Moderno',
    description: 'Laterais em fade com topo texturizado e franja curta e reta para frente.',
    compatibleFaceShapes: ['Oval', 'Retangular', 'Coracao', 'Triangular'],
    maintenanceLevel: 'Medio',
    styleCompatibility: ['Moderno', 'Despojado', 'Casual'],
    idealLength: 'Curto',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'crop', 'moderno'],
    stylingTips: 'Use pó modelador ou pomada matte para criar textura sem brilho.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's French crop haircut, blunt textured front fringe, clean fade on temples, piecey matte top texture, authentic hair strands, contemporary barber finish.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'textured-crop',
    name: 'Textured Crop + Low Fade',
    category: 'Urbano',
    description: 'Topo desfiado com mechas desconectadas e transição suave nas têmporas.',
    compatibleFaceShapes: ['Oval', 'Redondo', 'Triangular', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Medio',
    styleCompatibility: ['Moderno', 'Despojado', 'Casual', 'Marcante'],
    idealLength: 'Curto',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'texturizado', 'fade'],
    stylingTips: 'Excelente para dar movimento a cabelos lisos ou levemente ondulados.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's textured crop haircut, low fade taper on sides, messy defined top strands, matte styling, crisp natural hairline, ultra-realistic hair definition.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'pompadour',
    name: 'Pompadour Clássico',
    category: 'Retrô Premium',
    description: 'Topete alto e volumoso penteado para trás com acabamento polido e laterais alinhadas.',
    compatibleFaceShapes: ['Redondo', 'Quadrado', 'Triangular'],
    maintenanceLevel: 'Bastante',
    styleCompatibility: ['Classico', 'Executivo', 'Marcante'],
    idealLength: 'Medio',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'pompadour', 'corte premium'],
    stylingTips: 'Secador e escova redonda para dar estrutura, seguido de pomada pomade com brilho médio.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's classic pompadour haircut, voluminous upward and backward swept front quiff, neat tapered sides, elegant natural sheen, professional styling, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'quiff',
    name: 'Modern Quiff',
    category: 'Elegante',
    description: 'Topete frontal texturizado e natural com laterais em degradê médio.',
    compatibleFaceShapes: ['Oval', 'Redondo', 'Quadrado', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Medio',
    styleCompatibility: ['Moderno', 'Executivo', 'Casual'],
    idealLength: 'Medio',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'quiff', 'moderno'],
    stylingTips: 'Secador apontando para cima com fixação matte flexível.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's modern quiff haircut, textured upward flow in front, smooth mid taper fade on sides, natural hair movement, crisp hairline, 8k uhd resolution.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'slick-back',
    name: 'Slick Back',
    category: 'Executivo',
    description: 'Fios penteados totalmente para trás com elegância e sofisticação atemporal.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular'],
    maintenanceLevel: 'Medio',
    styleCompatibility: ['Classico', 'Executivo', 'Marcante'],
    idealLength: 'Medio',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'social', 'executivo'],
    stylingTips: 'Funciona muito bem com pomadas à base de água de fixação média a forte.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's slicked back hairstyle, medium length hair combed smoothly backward, neat tapered sides, sleek polished silhouette, natural hair sheen, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'side-part',
    name: 'Side Part (Divisão Lateral)',
    category: 'Gentleman',
    description: 'Corte tradicional repartido de lado, com linha bem definida e acabamento impecável.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular', 'Triangular', 'Nao sei'],
    maintenanceLevel: 'Pouco',
    styleCompatibility: ['Classico', 'Executivo', 'Natural'],
    idealLength: 'Medio',
    changeImpact: 'Pouco',
    suggestedServiceKeywords: ['corte social', 'corte tradicional', 'corte'],
    stylingTips: 'Pente fino para assentar a linha de divisão e pomada clássica.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic gentlemen's side part haircut, clean defined parting line, well-groomed scissor-trimmed sides, classic executive silhouette, authentic hair texture, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'corte-social',
    name: 'Corte Social Limpo',
    category: 'Tradicional',
    description: 'Laterais baixas na tesoura ou máquina alta, topo proporcional e pezinho alinhado.',
    compatibleFaceShapes: ['Oval', 'Redondo', 'Quadrado', 'Retangular', 'Triangular', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Pouco',
    styleCompatibility: ['Classico', 'Executivo', 'Natural'],
    idealLength: 'Curto',
    changeImpact: 'Pouco',
    suggestedServiceKeywords: ['corte social', 'corte', 'tradicional'],
    stylingTips: 'Extremamente prático no dia a dia, combina com qualquer ocasião.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic clean traditional men's social haircut, neat scissor-trimmed sides, balanced top length, tidy natural hairline contour, subtle matte finish, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'corte-executivo',
    name: 'Executivo Contemporâneo',
    category: 'Business',
    description: 'Tesoura e acabamento milimétrico, conferindo autoridade e postura profissional.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular', 'Nao sei'],
    maintenanceLevel: 'Pouco',
    styleCompatibility: ['Executivo', 'Classico'],
    idealLength: 'Medio',
    changeImpact: 'Pouco',
    suggestedServiceKeywords: ['corte', 'social', 'barba'],
    stylingTips: 'Manutenção mensal e hidratação leve periódica.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic contemporary executive haircut, precision scissor styling, refined temple blend, tidy contours, natural healthy hair sheen, executive barber finish.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'long-hair-layers',
    name: 'Corte Longo em Camadas',
    category: 'Longo',
    description: 'Cabelo de comprimento médio a longo com pontas desfiadas para caimento natural.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Coracao'],
    maintenanceLevel: 'Bastante',
    styleCompatibility: ['Longo', 'Despojado', 'Natural'],
    idealLength: 'Longo',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte longo', 'corte', 'lavagem'],
    stylingTips: 'Leave-in hidratante e secagem natural para preservar o balanço.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's layered medium-to-long hairstyle, flowing natural waves, soft shoulder-grazing texture, authentic hair movement, healthy hair sheen, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'curly-fade',
    name: 'Curly High Top + Taper',
    category: 'Cachos & Crespos',
    description: 'Volume no topo valorizando cachos naturais com laterais e nuca em degradê limpo.',
    compatibleFaceShapes: ['Oval', 'Redondo', 'Quadrado', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Medio',
    styleCompatibility: ['Moderno', 'Despojado', 'Natural', 'Marcante'],
    idealLength: 'Medio',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'cachos', 'fade'],
    stylingTips: 'Ativador de cachos e esponja twist ou fitagem para definição duradoura.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic men's defined curly high top haircut, voluminous defined natural coils on top, sharp razor taper fade on sides and back, crisp hairline lineup, 8k uhd.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
  {
    id: 'corte-despojado-surfer',
    name: 'Medium Flow / Despojado',
    category: 'Despojado',
    description: 'Comprimento médio penteado para trás e para os lados com aspecto livre e moderno.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular', 'Coracao'],
    maintenanceLevel: 'Pouco',
    styleCompatibility: ['Casual', 'Despojado', 'Natural', 'Longo'],
    idealLength: 'Medio',
    changeImpact: 'Medio',
    suggestedServiceKeywords: ['corte', 'tesoura', 'textura'],
    stylingTips: 'Spray de sal marinho (sea salt spray) para volume texturizado natural.',
    referenceImageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
    stylePrompt: "Apply photorealistic relaxed medium flow surfer haircut, swept back wavy hair strands, effortless matte texture, natural volume and movement, 8k uhd resolution.",
    negativePrompt: BASE_NEGATIVE_PROMPT,
    maskType: 'hair',
  },
];

export const BEARD_STYLES_CATALOG: BeardStyleItem[] = [
  {
    id: 'barba-por-fazer',
    name: 'Barba por Fazer (Stubble 3-5 dias)',
    description: 'Comprimento curto e desenhado no pescoço e bochechas, conferindo rusticidade sutil.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Redondo', 'Retangular', 'Triangular', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Pouco',
    idealWithHaircuts: ['low-fade', 'mid-fade', 'quiff', 'taper-fade', 'french-crop', 'corte-social'],
    stylingTips: 'Apare 2x por semana e mantenha a linha da garganta limpa a 2 dedos do pomo de adão.',
  },
  {
    id: 'short-boxed',
    name: 'Short Boxed Beard (Barba Alinhada)',
    description: 'Barba com formato retangular esculpido, comprimento uniforme e linhas simétricas.',
    compatibleFaceShapes: ['Oval', 'Redondo', 'Triangular', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Medio',
    idealWithHaircuts: ['low-fade', 'side-part', 'quiff', 'textured-crop', 'corte-executivo'],
    stylingTips: 'Óleo para barba para maciez e alinhamento com navalhete na barbearia a cada 15 dias.',
  },
  {
    id: 'barba-cheia',
    name: 'Barba Cheia (Full Beard)',
    description: 'Volume robusto nas bochechas e queixo, proporcionando imponência e presença.',
    compatibleFaceShapes: ['Oval', 'Triangular', 'Retangular', 'Coracao'],
    maintenanceLevel: 'Bastante',
    idealWithHaircuts: ['buzz-cut', 'skin-fade', 'taper-fade', 'slick-back', 'long-hair-layers'],
    stylingTips: 'Balm modelador diário, escova de cerdas naturais e hidratação profunda semanal.',
  },
  {
    id: 'barba-desenhada',
    name: 'Barba Desenhada em Fade',
    description: 'Transição suave entre a costeleta e o volume da barba, com linhas ultra nítidas.',
    compatibleFaceShapes: ['Redondo', 'Quadrado', 'Oval', 'Nao sei'],
    maintenanceLevel: 'Bastante',
    idealWithHaircuts: ['mid-fade', 'high-fade', 'skin-fade', 'curly-fade'],
    stylingTips: 'Requer retoque profissional frequente para manter a precisão do degradê facial.',
  },
  {
    id: 'cavanhaque-moderno',
    name: 'Cavanhaque Moderno',
    description: 'Foco no queixo e bigode interligados com bochechas raspadas e limpas.',
    compatibleFaceShapes: ['Quadrado', 'Redondo', 'Oval'],
    maintenanceLevel: 'Pouco',
    idealWithHaircuts: ['corte-social', 'low-fade', 'crew-cut', 'side-part'],
    stylingTips: 'Ideal para quem possui falhas nas laterais do rosto e quer destacar o queixo.',
  },
  {
    id: 'bigode-chevron',
    name: 'Bigode Chevron / Vintage',
    description: 'Bigode cheio cobrindo todo o lábio superior com resto do rosto raspado ou por fazer.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular'],
    maintenanceLevel: 'Medio',
    idealWithHaircuts: ['taper-fade', 'side-part', 'buzz-cut', 'medium-flow'],
    stylingTips: 'Cera para bigode nas pontas e corte milimétrico na linha do lábio.',
  },
  {
    id: 'barba-curta-degrade',
    name: 'Barba Curta com Degradê',
    description: 'Laterais muito curtas afinando o rosto com volume concentrado no queixo.',
    compatibleFaceShapes: ['Redondo', 'Quadrado', 'Triangular', 'Nao sei'],
    maintenanceLevel: 'Medio',
    idealWithHaircuts: ['low-fade', 'textured-crop', 'quiff', 'corte-executivo'],
    stylingTips: 'Efeito alongador visual imediato para rostos redondos ou mais largos.',
  },
  {
    id: 'rosto-liso',
    name: 'Rosto Liso (Barbeado Clássico)',
    description: 'Pele totalmente lisa com tratamento de toalha quente e pós-barba refrescante.',
    compatibleFaceShapes: ['Oval', 'Quadrado', 'Retangular', 'Coracao', 'Nao sei'],
    maintenanceLevel: 'Pouco',
    idealWithHaircuts: ['corte-social', 'side-part', 'corte-executivo', 'pompadour'],
    stylingTips: 'Toalha quente e hidratação para evitar foliculite.',
  },
];

export const COLOR_OPTIONS_CATALOG: ColorOptionItem[] = [
  {
    id: 'natural',
    name: 'Cor Natural & Brilho',
    tone: 'Tom original com realce',
    description: 'Preservação da tonalidade natural com banho de brilho e hidratação profunda.',
    maintenanceLevel: 'Pouco',
    careTips: 'Shampoo nutritivo e óleo finalizador para valorizar a cor original.',
  },
  {
    id: 'castanho-escuro',
    name: 'Castanho Escuro Intenso',
    tone: 'Castanho profundo',
    description: 'Tonalidade sóbria e marcante que uniformiza os fios e disfarça falhas.',
    maintenanceLevel: 'Pouco',
    careTips: 'Retoque a cada 30 a 45 dias conforme o crescimento da raiz.',
  },
  {
    id: 'castanho-claro',
    name: 'Castanho Claro / Avelã',
    tone: 'Avelã suave',
    description: 'Ilumina o semblante suavemente sem contraste agressivo.',
    maintenanceLevel: 'Medio',
    careTips: 'Utilize produtos com proteção UV para evitar oxidação.',
  },
  {
    id: 'loiro-dourado',
    name: 'Loiro Dourado / Mechas',
    tone: 'Loiro quente',
    description: 'Luzes ou descoloração suave para dar profundidade e estilo jovial.',
    maintenanceLevel: 'Medio',
    careTips: 'Máscara reconstrutora quinzenal após o processo de descoloração.',
  },
  {
    id: 'platinado',
    name: 'Platinado / Nevou',
    tone: 'Branco / Prata gélido',
    description: 'Visual moderno de alto impacto, febre nas barbearias brasileiras.',
    maintenanceLevel: 'Bastante',
    careTips: 'Shampoo matizador roxo 1x por semana e hidratação intensa obrigatória.',
  },
  {
    id: 'grisalho-matizado',
    name: 'Grisalho Matizado / Camuflagem',
    tone: 'Prata / Cinza nobre',
    description: 'Matização dos fios brancos ou camuflagem sutil para elegância madura.',
    maintenanceLevel: 'Medio',
    careTips: 'Shampoo desamarelador para manter os fios brancos/grisalhos prateados.',
  },
  {
    id: 'colorido-fantasia',
    name: 'Colorido / Fantasia (Azul / Vermelho)',
    tone: 'Vibrante',
    description: 'Estilo alternativo expressivo para quem busca identidade única.',
    maintenanceLevel: 'Bastante',
    careTips: 'Lavagens com água fria e shampoos sem sulfato para preservar a vivacidade.',
  },
];
